### ISSUE TITLE
Links quebrados

### ISSUE THREAD

**Issue by EdiJunior88** [iuricode/vagas-frontend#14]
Ao clicar nos links do readme, aparece um erro no encurtador **ERR_ADDRESS_INVALID**
 
![Desktop-screenshot](https://github.com/iuricode/vagas-frontend/assets/13875907/3c1f64eb-b00e-4952-872a-7f946d4f6592)

**Comment by iuricode** [comment]
Estranho, eu abri em outros navegadores e todos os links estão ok

**Comment by EdiJunior88** [comment]
> Estranho, eu abri em outros navegadores e todos os links estão ok

Estranho que aqui abre todos os outros sites de encurtador de links, menos esse encurtador br

**Comment by iuricode** [comment]
Consegue me recomendar outros encurtadores de links? Vou alterar esse

**Comment by iuricode** [comment]
Muito obrigado!
